#!/bin/bash -x
set -e
(
	cat ekb/latex.header
	pandoc -f markdown -t latex \
		docs/Tasks/Tk-MultipleItemsPerAppEntering.xml.txt
	cat ekb/latex.footer
) >test.latex
pdflatex test.latex
cp test.pdf /media/psf/Home/test.pdf
ssh mean open test.pdf
