#!/bin/bash
set -e
rm -f xml/*.xml.txt
rm -f xml/*.ditamap.txt
rm -rf docs/*  # don't delete .idmap file
mkdir -p docs
cd xml && (
	python ../ekb/dita-import.py ../docs *.xml
	python ../ekb/dita-import.py ../docs *.ditamap
)
