#!/usr/bin/env python
import os, sys

sys.path.append(os.path.abspath(os.path.dirname(sys.argv[0]) + '/..'))
os.environ['DJANGO_SETTINGS_MODULE'] = 'settings'

if len(sys.argv) != 2:
    sys.stderr.write("Usage: %s <document-dir>\n" % sys.argv[0])
    exit(1)

import ekb.load
ekb.load.index_docs(sys.argv[1])
