#!/usr/bin/env python
import os, sys

sys.path.append(os.path.abspath(os.path.dirname(sys.argv[0]) + '/..'))
os.environ['DJANGO_SETTINGS_MODULE'] = 'settings'
print sys.path

import ekb.load
for d in sys.argv[1:]:
    ekb.load.load_all(d)
